<?php
/**
 * BalanceSheetTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EquiblesStocks
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Stocks
 *
 * <h3>Rate limits</h3>                     Free subscriptions are subject to daily limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)<br />                     2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>
 *
 * OpenAPI spec version: v1
 * Contact: contact@equibles.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace EquiblesStocks;

/**
 * BalanceSheetTest Class Doc Comment
 *
 * @category    Class
 * @description BalanceSheet
 * @package     EquiblesStocks
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BalanceSheetTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BalanceSheet"
     */
    public function testBalanceSheet()
    {
    }

    /**
     * Test attribute "assets"
     */
    public function testPropertyAssets()
    {
    }

    /**
     * Test attribute "tangibleAssets"
     */
    public function testPropertyTangibleAssets()
    {
    }

    /**
     * Test attribute "currentAssets"
     */
    public function testPropertyCurrentAssets()
    {
    }

    /**
     * Test attribute "cashAndCashEquivalents"
     */
    public function testPropertyCashAndCashEquivalents()
    {
    }

    /**
     * Test attribute "cashAndShortTermInvestments"
     */
    public function testPropertyCashAndShortTermInvestments()
    {
    }

    /**
     * Test attribute "inventory"
     */
    public function testPropertyInventory()
    {
    }

    /**
     * Test attribute "currentNetReceivables"
     */
    public function testPropertyCurrentNetReceivables()
    {
    }

    /**
     * Test attribute "nonCurrentAssets"
     */
    public function testPropertyNonCurrentAssets()
    {
    }

    /**
     * Test attribute "propertyPlantEquipment"
     */
    public function testPropertyPropertyPlantEquipment()
    {
    }

    /**
     * Test attribute "accumulatedDepreciationAmortization"
     */
    public function testPropertyAccumulatedDepreciationAmortization()
    {
    }

    /**
     * Test attribute "intangibleAssets"
     */
    public function testPropertyIntangibleAssets()
    {
    }

    /**
     * Test attribute "intangibleAssetsExcludingGoodwill"
     */
    public function testPropertyIntangibleAssetsExcludingGoodwill()
    {
    }

    /**
     * Test attribute "goodwill"
     */
    public function testPropertyGoodwill()
    {
    }

    /**
     * Test attribute "investments"
     */
    public function testPropertyInvestments()
    {
    }

    /**
     * Test attribute "longTermInvestments"
     */
    public function testPropertyLongTermInvestments()
    {
    }

    /**
     * Test attribute "shortTermInvestments"
     */
    public function testPropertyShortTermInvestments()
    {
    }

    /**
     * Test attribute "otherCurrentAssets"
     */
    public function testPropertyOtherCurrentAssets()
    {
    }

    /**
     * Test attribute "otherNonCurrentAssets"
     */
    public function testPropertyOtherNonCurrentAssets()
    {
    }

    /**
     * Test attribute "liabilities"
     */
    public function testPropertyLiabilities()
    {
    }

    /**
     * Test attribute "currentLiabilities"
     */
    public function testPropertyCurrentLiabilities()
    {
    }

    /**
     * Test attribute "currentAccountsPayable"
     */
    public function testPropertyCurrentAccountsPayable()
    {
    }

    /**
     * Test attribute "deferredRevenue"
     */
    public function testPropertyDeferredRevenue()
    {
    }

    /**
     * Test attribute "currentDebt"
     */
    public function testPropertyCurrentDebt()
    {
    }

    /**
     * Test attribute "shortTermDebt"
     */
    public function testPropertyShortTermDebt()
    {
    }

    /**
     * Test attribute "nonCurrentLiabilities"
     */
    public function testPropertyNonCurrentLiabilities()
    {
    }

    /**
     * Test attribute "capitalLeaseObligations"
     */
    public function testPropertyCapitalLeaseObligations()
    {
    }

    /**
     * Test attribute "longTermDebt"
     */
    public function testPropertyLongTermDebt()
    {
    }

    /**
     * Test attribute "currentLongTermDebt"
     */
    public function testPropertyCurrentLongTermDebt()
    {
    }

    /**
     * Test attribute "longTermDebtNonCurrent"
     */
    public function testPropertyLongTermDebtNonCurrent()
    {
    }

    /**
     * Test attribute "shortLongTermDebtTotal"
     */
    public function testPropertyShortLongTermDebtTotal()
    {
    }

    /**
     * Test attribute "otherCurrentLiabilities"
     */
    public function testPropertyOtherCurrentLiabilities()
    {
    }

    /**
     * Test attribute "otherNonCurrentLiabilities"
     */
    public function testPropertyOtherNonCurrentLiabilities()
    {
    }

    /**
     * Test attribute "equity"
     */
    public function testPropertyEquity()
    {
    }

    /**
     * Test attribute "treasuryStock"
     */
    public function testPropertyTreasuryStock()
    {
    }

    /**
     * Test attribute "retainedEarnings"
     */
    public function testPropertyRetainedEarnings()
    {
    }

    /**
     * Test attribute "commonStock"
     */
    public function testPropertyCommonStock()
    {
    }

    /**
     * Test attribute "sharesOutstanding"
     */
    public function testPropertySharesOutstanding()
    {
    }

    /**
     * Test attribute "accumulatedOtherComprehensiveIncome"
     */
    public function testPropertyAccumulatedOtherComprehensiveIncome()
    {
    }

    /**
     * Test attribute "workingCapital"
     */
    public function testPropertyWorkingCapital()
    {
    }
}
