<?php
/**
 * CashFlowStatementTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EquiblesStocks
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Stocks
 *
 * <h3>Rate limits</h3>                     Free subscriptions are subject to daily limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)<br />                     2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>
 *
 * OpenAPI spec version: v1
 * Contact: contact@equibles.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace EquiblesStocks;

/**
 * CashFlowStatementTest Class Doc Comment
 *
 * @category    Class
 * @description CashFlowStatement
 * @package     EquiblesStocks
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CashFlowStatementTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CashFlowStatement"
     */
    public function testCashFlowStatement()
    {
    }

    /**
     * Test attribute "operatingCashFlow"
     */
    public function testPropertyOperatingCashFlow()
    {
    }

    /**
     * Test attribute "paymentsForOperatingActivities"
     */
    public function testPropertyPaymentsForOperatingActivities()
    {
    }

    /**
     * Test attribute "proceedsFromOperatingActivities"
     */
    public function testPropertyProceedsFromOperatingActivities()
    {
    }

    /**
     * Test attribute "changeInOperatingLiabilities"
     */
    public function testPropertyChangeInOperatingLiabilities()
    {
    }

    /**
     * Test attribute "changeInOperatingAssets"
     */
    public function testPropertyChangeInOperatingAssets()
    {
    }

    /**
     * Test attribute "depreciationDepletionAndAmortization"
     */
    public function testPropertyDepreciationDepletionAndAmortization()
    {
    }

    /**
     * Test attribute "capitalExpenditures"
     */
    public function testPropertyCapitalExpenditures()
    {
    }

    /**
     * Test attribute "changeInReceivables"
     */
    public function testPropertyChangeInReceivables()
    {
    }

    /**
     * Test attribute "changeInInventory"
     */
    public function testPropertyChangeInInventory()
    {
    }

    /**
     * Test attribute "profitLoss"
     */
    public function testPropertyProfitLoss()
    {
    }

    /**
     * Test attribute "investments"
     */
    public function testPropertyInvestments()
    {
    }

    /**
     * Test attribute "cashFlowFromInvestment"
     */
    public function testPropertyCashFlowFromInvestment()
    {
    }

    /**
     * Test attribute "cashFlowFromFinancing"
     */
    public function testPropertyCashFlowFromFinancing()
    {
    }

    /**
     * Test attribute "proceedsFromRepaymentsOfShortTermDebt"
     */
    public function testPropertyProceedsFromRepaymentsOfShortTermDebt()
    {
    }

    /**
     * Test attribute "paymentsForRepurchaseOfCommonStock"
     */
    public function testPropertyPaymentsForRepurchaseOfCommonStock()
    {
    }

    /**
     * Test attribute "paymentsForRepurchaseOfEquity"
     */
    public function testPropertyPaymentsForRepurchaseOfEquity()
    {
    }

    /**
     * Test attribute "paymentsForRepurchaseOfPreferredStock"
     */
    public function testPropertyPaymentsForRepurchaseOfPreferredStock()
    {
    }

    /**
     * Test attribute "dividendPayout"
     */
    public function testPropertyDividendPayout()
    {
    }

    /**
     * Test attribute "dividendPayoutCommonStock"
     */
    public function testPropertyDividendPayoutCommonStock()
    {
    }

    /**
     * Test attribute "dividendPayoutPreferredStock"
     */
    public function testPropertyDividendPayoutPreferredStock()
    {
    }

    /**
     * Test attribute "proceedsFromIssuanceOfCommonStock"
     */
    public function testPropertyProceedsFromIssuanceOfCommonStock()
    {
    }

    /**
     * Test attribute "proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet"
     */
    public function testPropertyProceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet()
    {
    }

    /**
     * Test attribute "proceedsFromIssuanceOfPreferredStock"
     */
    public function testPropertyProceedsFromIssuanceOfPreferredStock()
    {
    }

    /**
     * Test attribute "proceedsFromRepurchaseOfEquity"
     */
    public function testPropertyProceedsFromRepurchaseOfEquity()
    {
    }

    /**
     * Test attribute "proceedsFromSaleOfTreasuryStock"
     */
    public function testPropertyProceedsFromSaleOfTreasuryStock()
    {
    }

    /**
     * Test attribute "changeInCashAndCashEquivalents"
     */
    public function testPropertyChangeInCashAndCashEquivalents()
    {
    }

    /**
     * Test attribute "changeInExchangeRate"
     */
    public function testPropertyChangeInExchangeRate()
    {
    }

    /**
     * Test attribute "netIncome"
     */
    public function testPropertyNetIncome()
    {
    }

    /**
     * Test attribute "netBorrowings"
     */
    public function testPropertyNetBorrowings()
    {
    }

    /**
     * Test attribute "changeInWorkingCapital"
     */
    public function testPropertyChangeInWorkingCapital()
    {
    }

    /**
     * Test attribute "otherNonCashItems"
     */
    public function testPropertyOtherNonCashItems()
    {
    }

    /**
     * Test attribute "freeCashFlow"
     */
    public function testPropertyFreeCashFlow()
    {
    }
}
