<?php
/**
 * IncomeStatementTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EquiblesStocks
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Stocks
 *
 * <h3>Rate limits</h3>                     Free subscriptions are subject to daily limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)<br />                     2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>
 *
 * OpenAPI spec version: v1
 * Contact: contact@equibles.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace EquiblesStocks;

/**
 * IncomeStatementTest Class Doc Comment
 *
 * @category    Class
 * @description IncomeStatement
 * @package     EquiblesStocks
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IncomeStatementTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IncomeStatement"
     */
    public function testIncomeStatement()
    {
    }

    /**
     * Test attribute "grossProfit"
     */
    public function testPropertyGrossProfit()
    {
    }

    /**
     * Test attribute "revenue"
     */
    public function testPropertyRevenue()
    {
    }

    /**
     * Test attribute "costOfRevenue"
     */
    public function testPropertyCostOfRevenue()
    {
    }

    /**
     * Test attribute "costOfGoodsAndServicesSold"
     */
    public function testPropertyCostOfGoodsAndServicesSold()
    {
    }

    /**
     * Test attribute "operatingIncome"
     */
    public function testPropertyOperatingIncome()
    {
    }

    /**
     * Test attribute "sellingGeneralAndAdministrative"
     */
    public function testPropertySellingGeneralAndAdministrative()
    {
    }

    /**
     * Test attribute "researchAndDevelopment"
     */
    public function testPropertyResearchAndDevelopment()
    {
    }

    /**
     * Test attribute "operatingExpenses"
     */
    public function testPropertyOperatingExpenses()
    {
    }

    /**
     * Test attribute "investmentIncomeNet"
     */
    public function testPropertyInvestmentIncomeNet()
    {
    }

    /**
     * Test attribute "netInterestIncome"
     */
    public function testPropertyNetInterestIncome()
    {
    }

    /**
     * Test attribute "interestIncome"
     */
    public function testPropertyInterestIncome()
    {
    }

    /**
     * Test attribute "interestExpense"
     */
    public function testPropertyInterestExpense()
    {
    }

    /**
     * Test attribute "nonInterestIncome"
     */
    public function testPropertyNonInterestIncome()
    {
    }

    /**
     * Test attribute "otherNonOperatingIncome"
     */
    public function testPropertyOtherNonOperatingIncome()
    {
    }

    /**
     * Test attribute "depreciation"
     */
    public function testPropertyDepreciation()
    {
    }

    /**
     * Test attribute "depreciationAndAmortization"
     */
    public function testPropertyDepreciationAndAmortization()
    {
    }

    /**
     * Test attribute "incomeBeforeTax"
     */
    public function testPropertyIncomeBeforeTax()
    {
    }

    /**
     * Test attribute "incomeTaxExpense"
     */
    public function testPropertyIncomeTaxExpense()
    {
    }

    /**
     * Test attribute "interestAndDebtExpense"
     */
    public function testPropertyInterestAndDebtExpense()
    {
    }

    /**
     * Test attribute "netIncomeFromContinuingOperations"
     */
    public function testPropertyNetIncomeFromContinuingOperations()
    {
    }

    /**
     * Test attribute "comprehensiveIncomeNetOfTax"
     */
    public function testPropertyComprehensiveIncomeNetOfTax()
    {
    }

    /**
     * Test attribute "ebit"
     */
    public function testPropertyEbit()
    {
    }

    /**
     * Test attribute "ebitda"
     */
    public function testPropertyEbitda()
    {
    }

    /**
     * Test attribute "netIncome"
     */
    public function testPropertyNetIncome()
    {
    }

    /**
     * Test attribute "effectOfAccountingCharges"
     */
    public function testPropertyEffectOfAccountingCharges()
    {
    }

    /**
     * Test attribute "taxProvision"
     */
    public function testPropertyTaxProvision()
    {
    }

    /**
     * Test attribute "sellingAndMarketingExpenses"
     */
    public function testPropertySellingAndMarketingExpenses()
    {
    }

    /**
     * Test attribute "extraordinaryItems"
     */
    public function testPropertyExtraordinaryItems()
    {
    }
}
