<?php
/**
 * ScreenerRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EquiblesStocks
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Stocks
 *
 * <h3>Rate limits</h3>                     Free subscriptions are subject to daily limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)<br />                     2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>
 *
 * OpenAPI spec version: v1
 * Contact: contact@equibles.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace EquiblesStocks;

/**
 * ScreenerRequestTest Class Doc Comment
 *
 * @category    Class
 * @description ScreenerRequest
 * @package     EquiblesStocks
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ScreenerRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ScreenerRequest"
     */
    public function testScreenerRequest()
    {
    }

    /**
     * Test attribute "searchQuery"
     */
    public function testPropertySearchQuery()
    {
    }

    /**
     * Test attribute "exchangeIds"
     */
    public function testPropertyExchangeIds()
    {
    }

    /**
     * Test attribute "sectorIds"
     */
    public function testPropertySectorIds()
    {
    }

    /**
     * Test attribute "industryIds"
     */
    public function testPropertyIndustryIds()
    {
    }

    /**
     * Test attribute "marketCapMin"
     */
    public function testPropertyMarketCapMin()
    {
    }

    /**
     * Test attribute "marketCapMax"
     */
    public function testPropertyMarketCapMax()
    {
    }

    /**
     * Test attribute "betaMin"
     */
    public function testPropertyBetaMin()
    {
    }

    /**
     * Test attribute "betaMax"
     */
    public function testPropertyBetaMax()
    {
    }

    /**
     * Test attribute "forwardDividendMin"
     */
    public function testPropertyForwardDividendMin()
    {
    }

    /**
     * Test attribute "forwardDividendMax"
     */
    public function testPropertyForwardDividendMax()
    {
    }

    /**
     * Test attribute "forwardDividendYieldMin"
     */
    public function testPropertyForwardDividendYieldMin()
    {
    }

    /**
     * Test attribute "forwardDividendYieldMax"
     */
    public function testPropertyForwardDividendYieldMax()
    {
    }

    /**
     * Test attribute "shortRatioMin"
     */
    public function testPropertyShortRatioMin()
    {
    }

    /**
     * Test attribute "shortRatioMax"
     */
    public function testPropertyShortRatioMax()
    {
    }

    /**
     * Test attribute "sharesShortPercentageMin"
     */
    public function testPropertySharesShortPercentageMin()
    {
    }

    /**
     * Test attribute "sharesShortPercentageMax"
     */
    public function testPropertySharesShortPercentageMax()
    {
    }

    /**
     * Test attribute "sharesShortPreviousMonthPercentageMin"
     */
    public function testPropertySharesShortPreviousMonthPercentageMin()
    {
    }

    /**
     * Test attribute "sharesShortPreviousMonthPercentageMax"
     */
    public function testPropertySharesShortPreviousMonthPercentageMax()
    {
    }

    /**
     * Test attribute "analystRecommendationMin"
     */
    public function testPropertyAnalystRecommendationMin()
    {
    }

    /**
     * Test attribute "analystRecommendationMax"
     */
    public function testPropertyAnalystRecommendationMax()
    {
    }

    /**
     * Test attribute "performanceOneDayMin"
     */
    public function testPropertyPerformanceOneDayMin()
    {
    }

    /**
     * Test attribute "performanceOneDayMax"
     */
    public function testPropertyPerformanceOneDayMax()
    {
    }

    /**
     * Test attribute "performanceOneWeekMin"
     */
    public function testPropertyPerformanceOneWeekMin()
    {
    }

    /**
     * Test attribute "performanceOneWeekMax"
     */
    public function testPropertyPerformanceOneWeekMax()
    {
    }

    /**
     * Test attribute "performanceTwoWeeksMin"
     */
    public function testPropertyPerformanceTwoWeeksMin()
    {
    }

    /**
     * Test attribute "performanceTwoWeeksMax"
     */
    public function testPropertyPerformanceTwoWeeksMax()
    {
    }

    /**
     * Test attribute "performanceOneMonthMin"
     */
    public function testPropertyPerformanceOneMonthMin()
    {
    }

    /**
     * Test attribute "performanceOneMonthMax"
     */
    public function testPropertyPerformanceOneMonthMax()
    {
    }

    /**
     * Test attribute "performanceThreeMonthsMin"
     */
    public function testPropertyPerformanceThreeMonthsMin()
    {
    }

    /**
     * Test attribute "performanceThreeMonthsMax"
     */
    public function testPropertyPerformanceThreeMonthsMax()
    {
    }

    /**
     * Test attribute "performanceOneYearMin"
     */
    public function testPropertyPerformanceOneYearMin()
    {
    }

    /**
     * Test attribute "performanceOneYearMax"
     */
    public function testPropertyPerformanceOneYearMax()
    {
    }

    /**
     * Test attribute "performanceThreeYearsMin"
     */
    public function testPropertyPerformanceThreeYearsMin()
    {
    }

    /**
     * Test attribute "performanceThreeYearsMax"
     */
    public function testPropertyPerformanceThreeYearsMax()
    {
    }

    /**
     * Test attribute "performanceFiveYearsMin"
     */
    public function testPropertyPerformanceFiveYearsMin()
    {
    }

    /**
     * Test attribute "performanceFiveYearsMax"
     */
    public function testPropertyPerformanceFiveYearsMax()
    {
    }

    /**
     * Test attribute "performanceTenYearsMin"
     */
    public function testPropertyPerformanceTenYearsMin()
    {
    }

    /**
     * Test attribute "performanceTenYearsMax"
     */
    public function testPropertyPerformanceTenYearsMax()
    {
    }

    /**
     * Test attribute "performanceTwentyYearsMin"
     */
    public function testPropertyPerformanceTwentyYearsMin()
    {
    }

    /**
     * Test attribute "performanceTwentyYearsMax"
     */
    public function testPropertyPerformanceTwentyYearsMax()
    {
    }

    /**
     * Test attribute "epsGrowthOneYearMin"
     */
    public function testPropertyEpsGrowthOneYearMin()
    {
    }

    /**
     * Test attribute "epsGrowthOneYearMax"
     */
    public function testPropertyEpsGrowthOneYearMax()
    {
    }

    /**
     * Test attribute "epsGrowthTwoYearsMin"
     */
    public function testPropertyEpsGrowthTwoYearsMin()
    {
    }

    /**
     * Test attribute "epsGrowthTwoYearsMax"
     */
    public function testPropertyEpsGrowthTwoYearsMax()
    {
    }

    /**
     * Test attribute "epsGrowthThreeYearsMin"
     */
    public function testPropertyEpsGrowthThreeYearsMin()
    {
    }

    /**
     * Test attribute "epsGrowthThreeYearsMax"
     */
    public function testPropertyEpsGrowthThreeYearsMax()
    {
    }

    /**
     * Test attribute "epsGrowthFiveYearsMin"
     */
    public function testPropertyEpsGrowthFiveYearsMin()
    {
    }

    /**
     * Test attribute "epsGrowthFiveYearsMax"
     */
    public function testPropertyEpsGrowthFiveYearsMax()
    {
    }

    /**
     * Test attribute "epsGrowthTenYearsMin"
     */
    public function testPropertyEpsGrowthTenYearsMin()
    {
    }

    /**
     * Test attribute "epsGrowthTenYearsMax"
     */
    public function testPropertyEpsGrowthTenYearsMax()
    {
    }

    /**
     * Test attribute "epsGrowthTwentyYearsMin"
     */
    public function testPropertyEpsGrowthTwentyYearsMin()
    {
    }

    /**
     * Test attribute "epsGrowthTwentyYearsMax"
     */
    public function testPropertyEpsGrowthTwentyYearsMax()
    {
    }

    /**
     * Test attribute "peMin"
     */
    public function testPropertyPeMin()
    {
    }

    /**
     * Test attribute "peMax"
     */
    public function testPropertyPeMax()
    {
    }

    /**
     * Test attribute "pegMin"
     */
    public function testPropertyPegMin()
    {
    }

    /**
     * Test attribute "pegMax"
     */
    public function testPropertyPegMax()
    {
    }

    /**
     * Test attribute "priceFcfMin"
     */
    public function testPropertyPriceFcfMin()
    {
    }

    /**
     * Test attribute "priceFcfMax"
     */
    public function testPropertyPriceFcfMax()
    {
    }

    /**
     * Test attribute "bookValuePerShareMin"
     */
    public function testPropertyBookValuePerShareMin()
    {
    }

    /**
     * Test attribute "bookValuePerShareMax"
     */
    public function testPropertyBookValuePerShareMax()
    {
    }

    /**
     * Test attribute "priceBookValuePerShareMin"
     */
    public function testPropertyPriceBookValuePerShareMin()
    {
    }

    /**
     * Test attribute "priceBookValuePerShareMax"
     */
    public function testPropertyPriceBookValuePerShareMax()
    {
    }

    /**
     * Test attribute "payoutMin"
     */
    public function testPropertyPayoutMin()
    {
    }

    /**
     * Test attribute "payoutMax"
     */
    public function testPropertyPayoutMax()
    {
    }

    /**
     * Test attribute "debtToEquityMin"
     */
    public function testPropertyDebtToEquityMin()
    {
    }

    /**
     * Test attribute "debtToEquityMax"
     */
    public function testPropertyDebtToEquityMax()
    {
    }

    /**
     * Test attribute "grossMarginMin"
     */
    public function testPropertyGrossMarginMin()
    {
    }

    /**
     * Test attribute "grossMarginMax"
     */
    public function testPropertyGrossMarginMax()
    {
    }

    /**
     * Test attribute "operatingMarginMin"
     */
    public function testPropertyOperatingMarginMin()
    {
    }

    /**
     * Test attribute "operatingMarginMax"
     */
    public function testPropertyOperatingMarginMax()
    {
    }

    /**
     * Test attribute "profitMarginMin"
     */
    public function testPropertyProfitMarginMin()
    {
    }

    /**
     * Test attribute "profitMarginMax"
     */
    public function testPropertyProfitMarginMax()
    {
    }

    /**
     * Test attribute "priceToSalesMin"
     */
    public function testPropertyPriceToSalesMin()
    {
    }

    /**
     * Test attribute "priceToSalesMax"
     */
    public function testPropertyPriceToSalesMax()
    {
    }

    /**
     * Test attribute "buybacksThreeMonthsMin"
     */
    public function testPropertyBuybacksThreeMonthsMin()
    {
    }

    /**
     * Test attribute "buybacksThreeMonthsMax"
     */
    public function testPropertyBuybacksThreeMonthsMax()
    {
    }

    /**
     * Test attribute "buybacksSixMonthsMin"
     */
    public function testPropertyBuybacksSixMonthsMin()
    {
    }

    /**
     * Test attribute "buybacksSixMonthsMax"
     */
    public function testPropertyBuybacksSixMonthsMax()
    {
    }

    /**
     * Test attribute "buybacksOneYearMin"
     */
    public function testPropertyBuybacksOneYearMin()
    {
    }

    /**
     * Test attribute "buybacksOneYearMax"
     */
    public function testPropertyBuybacksOneYearMax()
    {
    }

    /**
     * Test attribute "buybacksTwoYearsMin"
     */
    public function testPropertyBuybacksTwoYearsMin()
    {
    }

    /**
     * Test attribute "buybacksTwoYearsMax"
     */
    public function testPropertyBuybacksTwoYearsMax()
    {
    }

    /**
     * Test attribute "buybacksThreeYearsMin"
     */
    public function testPropertyBuybacksThreeYearsMin()
    {
    }

    /**
     * Test attribute "buybacksThreeYearsMax"
     */
    public function testPropertyBuybacksThreeYearsMax()
    {
    }

    /**
     * Test attribute "buybacksFiveYearsMin"
     */
    public function testPropertyBuybacksFiveYearsMin()
    {
    }

    /**
     * Test attribute "buybacksFiveYearsMax"
     */
    public function testPropertyBuybacksFiveYearsMax()
    {
    }

    /**
     * Test attribute "buybacksTenYearsMin"
     */
    public function testPropertyBuybacksTenYearsMin()
    {
    }

    /**
     * Test attribute "buybacksTenYearsMax"
     */
    public function testPropertyBuybacksTenYearsMax()
    {
    }

    /**
     * Test attribute "buybacksTwentyYearsMin"
     */
    public function testPropertyBuybacksTwentyYearsMin()
    {
    }

    /**
     * Test attribute "buybacksTwentyYearsMax"
     */
    public function testPropertyBuybacksTwentyYearsMax()
    {
    }

    /**
     * Test attribute "potentialUpside"
     */
    public function testPropertyPotentialUpside()
    {
    }
}
